# Generated by Django 5.2.6 on 2025-09-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='profile_image',
            field=models.ImageField(blank=True, default='defaults/default.png', null=True, upload_to='profile/'),
        ),
    ]
