# Generated by Django 5.2.6 on 2025-09-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_aboutme_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='lottie_url',
            field=models.URLField(blank=True),
        ),
    ]
