# Generated by Django 5.2.6 on 2025-09-26 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_mediafile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaFile',
        ),
    ]
