# Generated by Django 5.2.6 on 2026-05-17 12:06

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_mediafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', validators=[home.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cv',
            name='file',
            field=models.FileField(upload_to='cv/', validators=[home.models.validate_file_extension]),
        ),
    ]
