# Generated by Django 5.2.6 on 2026-05-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_certificate_file_alter_contactmessage_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='file',
        ),
        migrations.AddField(
            model_name='cv',
            name='file_url',
            field=models.URLField(blank=True, default='', help_text='Google Drive, Dropbox veya Cloudinary linki yapıştırın', max_length=500),
        ),
    ]
