# Generated by Django 5.2.6 on 2025-09-23 13:09

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_certificate_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='details',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='hero',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='details',
            field=tinymce.models.HTMLField(),
        ),
    ]
