# Generated by Django 5.2.6 on 2026-05-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_cv_file_cv_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='file_url',
        ),
        migrations.AddField(
            model_name='cv',
            name='file',
            field=models.FileField(blank=True, default='', storage='db_file_storage.storage.DatabaseFileStorage', upload_to='home.CV/file/filename'),
        ),
    ]
