# Generated by Django 5.2.6 on 2026-05-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_cv_file_url_cv_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='file',
        ),
        migrations.AddField(
            model_name='cv',
            name='file_url',
            field=models.URLField(blank=True, default='', help_text='CV linkini buraya yapıştırın (Google Drive, Dropbox vb.)', max_length=500),
        ),
    ]
