# Generated by Django 5.2.6 on 2026-05-17 14:00

import home.db_storage
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_storedfile_alter_aboutme_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='file_url',
        ),
        migrations.AddField(
            model_name='cv',
            name='file',
            field=models.FileField(blank=True, storage=home.db_storage.DatabaseStorage(), upload_to='', validators=[home.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, null=True, storage=home.db_storage.DatabaseStorage(), upload_to='', validators=[home.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=home.db_storage.DatabaseStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, null=True, storage=home.db_storage.DatabaseStorage(), upload_to=''),
        ),
    ]
