# Generated by Django 5.2.6 on 2026-05-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_cv_file_url_cv_file_alter_certificate_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedfile',
            name='key',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
