# Generated by Django 5.2.6 on 2026-05-17 15:04

import home.db_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_storedfile_key_maxlength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='lottie_url',
        ),
        migrations.AddField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=home.db_storage.DatabaseStorage(), upload_to=''),
        ),
    ]
